const List<String> teamsNamesList = [
  'AC Milan',
  'Ajax',
  'Arsenal',
  'Atletico Madrid',
  'Barcelona',
  'Bayern Munchen',
  'Chelsea',
  'Inter Milan',
  'Juventus',
  'Lazio',
  'Liverpool',
  'Manchester City',
  'Manchester United',
  'PSG',
  'Real Madrid',
  'Roma',
  'Sevilla',
  'Tottenham'
];
